lib/myKitchen_web/router.ex
defmodule MyKitchenWeb.Router do
  use MyKitchenWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug MyKitchenWeb.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MyKitchenWeb do
    pipe_through :browser # Use the default browser stack

    resources "/", KitchenController
  end

  scope "/user", MyKitchenWeb do
    pipe_through :browser # Use the default browser stack

    get "login", UserController, :login
    resources "/", UserController
  end

  # Other scopes may use custom stacks.
  # scope "/api", MyKitchenWeb do
  #   pipe_through :api
  # end
end

lib/myKitchen/application.ex
defmodule MyKitchen.Application do
  use Application

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the Ecto repository
      supervisor(MyKitchen.Repo, []),
      # Start the endpoint when the application starts
      supervisor(MyKitchenWeb.Endpoint, []),
      # Start your own worker by calling: MyKitchen.Worker.start_link(arg1, arg2, arg3)
      # worker(MyKitchen.Worker, [arg1, arg2, arg3]),
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: MyKitchen.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    MyKitchenWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/myKitchen/pantry/user.ex
defmodule MyKitchen.Pantry.User do
  use Ecto.Schema

  import Ecto.Changeset

  alias Comeonin.Bcrypt

  schema "pantry_user" do
    field :email, :string
    field :name, :string
    field :password, :string
    field :password_hash, :string

    timestamps()
  end

  @doc false
  def changeset(user_changeset, params \\ %{}) do
    user_changeset
    |> cast(params, [:name, :email, :password])
    |> unique_constraint(:email, downcase: true)
    |> validate_required([:name, :email, :password])
    |> IO.inspect()
    |> password_flow()
  end

  defp password_flow(user_changeset, params \\ %{}) do
    user_changeset
    |> cast(params, [:password])
    |> validate_required([:password])
    |> hash_password()
  end

  defp hash_password(user_changeset) do
    case user_changeset do
      %Ecto.Changeset{valid?: true} ->
        password = get_change(user_changeset, :password)
        user_changeset
        |> put_change(:password_hash, Bcrypt.hashpwsalt(password))
        |> put_change(:password, nil)
      _ ->
        user_changeset
    end
  end
end

lib/myKitchen/repo.ex
defmodule MyKitchen.Repo do
  use Ecto.Repo, otp_app: :myKitchen

  @doc """
  Dynamically loads the repository url from the
  DATABASE_URL environment variable.
  """
  def init(_, opts) do
    {:ok, Keyword.put(opts, :url, System.get_env("DATABASE_URL"))}
  end
end

lib/myKitchen_web/controllers/kitchen_controller.ex
defmodule MyKitchenWeb.KitchenController do
  use MyKitchenWeb, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

lib/myKitchen_web/controllers/page_controller.ex
defmodule MyKitchenWeb.PageController do
  use MyKitchenWeb, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

lib/myKitchen_web/controllers/user_controller.ex
defmodule MyKitchenWeb.UserController do
  use MyKitchenWeb, :controller

  alias MyKitchen.Pantry.User
  alias MyKitchen.Repo

  def new(conn, _params) do
    user_changeset = User.changeset(%User{}, %{})

    render conn, "signup.html", changeset: user_changeset
  end

  def create(conn, %{"user" => user}) do
    user_changeset = User.changeset(%User{}, %{"name" => user["name"], "email" => user["email"], "password" => user["password"]})

    case Repo.insert(user_changeset) do
      {:ok, _} ->
        conn
        |> put_flash(:info, "Account created!")
        |> redirect(to: kitchen_path(conn, :index))
      {:error, user_changeset} ->
        render conn, "signup.html", changeset: user_changeset
    end
  end

  def login(conn, _params) do
    user_changeset = User.changeset(%User{}, %{})

    render conn, "login.html", changeset: user_changeset
  end
end

lib/myKitchen_web/views/error_view.ex
defmodule MyKitchenWeb.ErrorView do
  use MyKitchenWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/myKitchen_web/views/kitchen_view.ex
defmodule MyKitchenWeb.KitchenView do
  use MyKitchenWeb, :view
end

lib/myKitchen_web/views/layout_view.ex
defmodule MyKitchenWeb.LayoutView do
  use MyKitchenWeb, :view
end

lib/myKitchen_web/views/user_view.ex
defmodule MyKitchenWeb.UserView do
  use MyKitchenWeb, :view
end

lib/myKitchen_web/templates/kitchen/index.html.eex
<b> Index </b>

lib/myKitchen_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello MyKitchen!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <nav>
      <h1 class="logo">MyKitchenApp</h1>
      <div class="navlinks">
        <a href="#">Home</a>
        <%= link "Login", to: user_path(@conn, :login) %>
        <%= link "Signup", to: user_path(@conn, :new) %>
      </div>
    </nav>
    <div class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/myKitchen_web/templates/user/login.html.eex
<h3>Login</h3>

<%= form_for @changeset, user_path(@conn, :login), fn f -> %>
  <div class="form-group">
    <%= email_input f, :email, placeholder: "email", class: "form-control" %>
    <%= error_tag f, :email %>
    <%= password_input f, :password, placeholder: "password", class: "form-control" %>
    <%= error_tag f, :password %>
  </div>
  <%= submit "Login", class: "btn btn-primary" %>
<% end %>

lib/myKitchen_web/templates/user/signup.html.eex
<h3>Signup</h3>

<%= form_for @changeset, user_path(@conn, :create), fn f -> %>
  <div class="form-group">
    <%= text_input f, :name, placeholder: "name", class: "form-control" %>
    <%= error_tag f, :name %>
    <%= email_input f, :email, placeholder: "email", class: "form-control" %>
    <%= error_tag f, :email %>
    <%= password_input f, :password, placeholder: "password", class: "form-control" %>
    <%= error_tag f, :password %>
  </div>
  <%= submit "Signup", class: "btn btn-primary" %>
<% end %>